import Navbar from "./Components/Navbar"
export const metadata = {
    title: 'Frontend',
    description: 'Generated by Next.js',
  }
  
export default function RootLayout({ children }) {
    return (
      <html lang="en">
        
        <body>
        <Navbar/>
        {children}
        </body>
      </html>
    )
  }